baseURL = 'https://blogs.decodegeek.co.in/'
languageCode = 'en-us'

title = 'Decoding Dev&Ops'
theme = "hyde-hyde"

paginate = 5
publishDir = "public"
googleAnalytics = "UA-213179883-1"
enableEmoji = true
summarylength = 30

[permalinks]
  fixed = ":title"

[params]
  author = "Vivek Sheshadri"
  title = "Decode DevOps"
  description = "Dev, Ops, & Code."
  authorimage = "avatar.jpg"
  dateformat = "Jan 2, 2006"
  highlightjs = true
  highlightjsstyle = "github"

  # Table of contents
  toc = "hugo"
  NewsletterSignup = "https://tinyletter.com/DecodeGeek"

[params.social]
    github = "TechnicalVegeta"
    twitter = "viv007s"
    linkedin = "vivek-s-028b5117"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "Subscribe"
    weight = 99
    identifier = "Subscribe"
    url = "/Subscribe/"

[[menu.main]]
    name = "About"
    weight = 1
    identifier = "About"
    url = "/About/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"