baseURL = 'https://blogs.decodegeek.co.in/'
languageCode = 'en-us'

title = 'Decoding Dev&Ops'
theme = "hyde-hyde"

paginate = 5
publishDir = "public"
googleAnalytics = "UA-213179883-1"
enableEmoji = true
summarylength = 30

[permalinks]
  fixed = ":title"

## Site settings
[params]
  author = "Vivek Sheshadri"
  title = "Decode DevOps"
  description = "Knowledge share on Dev, Ops, & Code."
  authorimage = "avatar.jpg"
  dateformat = "Jan 2, 2006"
  highlightjs = true
  highlightjsstyle = "github"

# sidebar, copyright & license
  #logoimage = "favicon.png"
  copyright = "Vivek S"
  since = 2021
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  showBuiltWith = true

  # Table of contents
  toc = "hugo"
  NewsletterSignup = "https://tinyletter.com/DecodeGeek"

[params.social]
    github = "TechnicalVegeta"
    twitter = "viv007s"
    linkedin = "vivek-s-028b5117"
    email =  "technical.blobs@decodegeek.co.in"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "Subscribe"
    weight = 99
    identifier = "Subscribe"
    url = "/Subscribe/"
[[menu.main]]
    name = "About"
    weight = 1
    identifier = "About"
    url = "/About/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"