baseURL = 'https://blogs.decodegeek.co.in/'
languageCode = 'en-us'

title = 'Learning & Decoding Dev&Ops'
theme = "hyde-hyde"

paginate = 5
publishDir = "public"
googleAnalytics = "UA-213179883-1"
enableEmoji = true
summarylength = 30

[permalinks]
  fixed = ":title"

## Site settings
[params]
  author = "Vivek Sheshadri"
  title = "Decode DevOps"
  description = "Knowledge share on Dev, Ops, & Code."
  authorimage = "avatar.jpg"
  dateformat = "Jan 2, 2006"
  highlightjs = true
  highlightjsstyle = "github"
  relatedPosts = true
# highlightjslanguages = ["swift", "objectivec"]
  mainSections = ["posts"]
# include_toc = false
  GraphCommentId = "Decode-DevOps"

# sidebar, copyright & license
  #logoimage = "favicon.png"
  copyright = "Vivek Sheshadri"
  since = 2021
# license = "CC BY-SA 4.0"
# licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  showBuiltWith = false

  # Table of contents
  toc = "hugo"
  NewsletterSignup = "https://tinyletter.com/DecodeGeek"

[params.social]
    github = "TechnicalVegeta"
    twitter = "viv007s"
    linkedin = "vivek-s-028b5117"
    email =  "technical.blobs@decodegeek.co.in"
  # gravatar = "your.email@domain.com"

[params.meta]
    description = "Passing on my learnings about Programming on Go, Operations on Cloud, Microservice, and DevOps Automation, so you don't have to waste as many hours as I did trying to figure out how to make it work."
    keywords = "Go, Powershell, Azure, Kubernetes, Docker, Rancher, k3d, Azure DevOps, k3s, Git, Terraform"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "Subscribe"
    weight = 99
    identifier = "Subscribe"
    url = "/Subscribe/"
[[menu.main]]
    name = "About"
    weight = 1
    identifier = "About"
    url = "/About/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"